# Generated by Django 5.2.5 on 2025-08-24 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name', max_length=50)),
                ('color', models.CharField(blank=True, default='#007BFF', help_text='Color code for category (hex format)', max_length=7, null=True)),
                ('description', models.TextField(blank=True, help_text='Category description', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who created this category', on_delete=django.db.models.deletion.CASCADE, related_name='custom_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Custom Category',
                'verbose_name_plural': 'Custom Categories',
                'ordering': ['name'],
                'unique_together': {('name', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Task title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Task description', null=True)),
                ('due_date', models.DateTimeField(blank=True, help_text='Task due date', null=True)),
                ('priority', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', help_text='Task priority level', max_length=10)),
                ('category', models.CharField(blank=True, choices=[('WORK', 'Work'), ('PERSONAL', 'Personal'), ('FITNESS', 'Fitness'), ('SHOPPING', 'Shopping'), ('HEALTH', 'Health'), ('EDUCATION', 'Education'), ('FINANCE', 'Finance'), ('OTHER', 'Other')], help_text='Default system category', max_length=15, null=True)),
                ('is_completed', models.BooleanField(default=False, help_text='Task completion status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('custom_category', models.ForeignKey(blank=True, help_text='Custom user-defined category', null=True, on_delete=django.db.models.deletion.SET_NULL, to='task.category')),
                ('user', models.ForeignKey(help_text='User who created this task', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
